config/routes.rb
Rails.application.routes.draw do
  root 'links#index'
  resources :links, only: [:index, :create, :list, :destroy]
  get '/link/:identifier', to: 'links#show', as: :short
  get 'list', to: 'links#list', as: 'list'
  get '/stats/:id', to: 'stats#show', as: :statistics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord

  validates :base_url, presence: true
  validates :base_url, uniqueness: true
  validates_length_of :base_url, maximum: 250

  has_many :stats, dependent: :delete_all
  before_validation :generate_identifier

  def short
    Rails.application.routes.url_helpers.short_url(identifier: self.identifier)
  end

  private
  def generate_identifier
    self.identifier = SecureRandom.uuid[0..5]
  end
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :set_link, only: [:index, :create, :destroy]
  before_action :get_links, only: [:list]

  def index
  end

  def create
    @link.update(link_params)
    begin @link.save!
      flash[:success] = t('link.validate.create.success')
    rescue
      flash[:danger] = t('link.validate.create.error')
    end

    redirect_to root_path
  end

  def list
  end

  def show
    begin
      link = Link.find_by_identifier(params[:identifier])
      Stat.create(link_id: link.id)
      redirect_to link.base_url
    rescue
      flash[:danger] = t('link.show.error')
      redirect_to root_path
    end
  end

  def destroy
    begin @link.destroy
      flash[:success] = t('link.destroy.success')
    rescue
      flash[:danger] = t('link.destroy.error')
    end

    redirect_to list_path
  end

  private
  def link_params
    params.require(:link).permit(:base_url)
  end

  def set_link
    @link = (params[:id].present?) ? Link.find(params[:id]) : Link.new
  end

  def get_links
    @links = Link.all
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def show
    @custom_url = Link.find(params[:id]).short
    @stats = Stat.where(link_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper

end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.haml
!!!
%html.h-100{:lang => "en"}
  %head
    %title Wizville - URL Shortener
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'


    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css", :integrity => "sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p", :src => "https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"}
    %link{:href => "https://getbootstrap.com/docs/5.1/examples/cover/cover.css", :rel => "stylesheet"}/

  %body.d-flex.h-100.text-center.text-white.bg-dark
    .cover-container.d-flex.w-100.h-100.p-3.mx-auto.flex-column
      = render 'pages/header'

      -#show flash message
      - flash.each do |type, msg|
        %div{:class => "alert alert-#{type}", :role => "alert"}
          = msg

      = yield
      = render 'pages/footer'

app/views/links/index.html.haml
%main.px-3
  %h3 Shorten your url
  %br/
  = form_for @link, url: { action: "create" } do |f|
    .form-group
      = f.url_field :base_url, class: 'form-control'
      %br/
      = f.submit 'Shortener', class: 'btn btn-primary'

app/views/links/list.html.haml
%table.table{:style => "color:white;"}
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Base URL
      %th{:scope => "col"} Generate URL
      %th{:scope => "col"}
      %th{:scope => "col"}
  %tbody
    - @links.each do |link|
      %tr
        %th{:scope => "row"}= link.id
        %td= link.base_url
        %td= link_to link.short, link.short, target: "_blank"
        %td= link_to 'delete', link_path(link.id), class: 'btn btn-danger', data: {confirm: 'Are you sure ?', method: 'delete'}
        %td= link_to 'stats', statistics_path(link.id), class: 'btn btn-primary'

app/views/pages/_footer.html.haml
%footer.mt-auto.text-white-50
  %p Author Jérémy Pestelard

app/views/pages/_header.html.haml
%header.mb-auto
  %div
    %h3.float-md-start.mb-0 Wizville Url Shortener
    %nav.nav.nav-masthead.justify-content-center.float-md-end
      = link_to 'Shortener', root_path, class: "nav-link #{(controller.action_name.eql? 'index') ? 'active' : ''}"
      = link_to 'Url list', list_path, class: "nav-link #{(%w{list show}.include? controller.action_name) ? 'active' : ''}"

app/views/stats/show.html.haml
= javascript_include_tag 'application'

%h1 URL Statistics
= link_to @custom_url, @custom_url, target: "_blank"
= line_chart @stats.group_by_minute(:created_at).count